set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN P1  IOSTANDARD LVCMOS33} [get_ports rst]

set_property -dict {PACKAGE_PIN P5  IOSTANDARD LVCMOS33} [get_ports S3]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS33} [get_ports din]
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS33} [get_ports dout]

set_property PACKAGE_PIN A18 [get_ports led_en[7]]
set_property PACKAGE_PIN A20 [get_ports led_en[6]]
set_property PACKAGE_PIN B20 [get_ports led_en[5]]
set_property PACKAGE_PIN E18 [get_ports led_en[4]]
set_property PACKAGE_PIN F18 [get_ports led_en[3]]
set_property PACKAGE_PIN D19 [get_ports led_en[2]]
set_property PACKAGE_PIN E19 [get_ports led_en[1]]
set_property PACKAGE_PIN C19 [get_ports led_en[0]]


set_property PACKAGE_PIN F15 [get_ports led[0]]
set_property PACKAGE_PIN F13 [get_ports led[1]]
set_property PACKAGE_PIN F14 [get_ports led[2]]
set_property PACKAGE_PIN F16 [get_ports led[3]]
set_property PACKAGE_PIN E17 [get_ports led[4]]
set_property PACKAGE_PIN C14 [get_ports led[5]]
set_property PACKAGE_PIN C15 [get_ports led[6]]
set_property PACKAGE_PIN E13 [get_ports led[7]]


set_property PACKAGE_PIN W4 [get_ports sw[0]]
set_property PACKAGE_PIN R4 [get_ports sw[1]]
set_property PACKAGE_PIN T4 [get_ports sw[2]]
set_property PACKAGE_PIN T5 [get_ports sw[3]]
set_property PACKAGE_PIN U5 [get_ports sw[4]]
set_property PACKAGE_PIN W6 [get_ports sw[5]]
set_property PACKAGE_PIN W5 [get_ports sw[6]]
set_property PACKAGE_PIN U6 [get_ports sw[7]]

set_property IOSTANDARD LVCMOS18 [get_ports led_en[0]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[1]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[2]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[3]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[4]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[5]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[6]]
set_property IOSTANDARD LVCMOS18 [get_ports led_en[7]]
set_property IOSTANDARD LVCMOS18 [get_ports led[0]]
set_property IOSTANDARD LVCMOS18 [get_ports led[1]]
set_property IOSTANDARD LVCMOS18 [get_ports led[2]]
set_property IOSTANDARD LVCMOS18 [get_ports led[3]]
set_property IOSTANDARD LVCMOS18 [get_ports led[4]]
set_property IOSTANDARD LVCMOS18 [get_ports led[5]]
set_property IOSTANDARD LVCMOS18 [get_ports led[6]]
set_property IOSTANDARD LVCMOS18 [get_ports led[7]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[4]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[5]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[6]]
set_property IOSTANDARD LVCMOS18 [get_ports sw[7]]